name: Main

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    steps:
    - name: Start Setup
      run: echo "start setup"

    - name: Finish Setup
      run: echo "finish setup"

  build:
    needs: setup
    uses: ./.github/workflows/build.yml

  testing:
    needs: build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/integration-tests.yml
