name: Main workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Start Setup
      run: echo "start setup"

    - name: Finish Setup
      run: echo "finish setup"

  build:
    uses: ./.github/workflows/build.yml

  testing:
    uses: ./.github/workflows/reusable-workflow.yml
