name: Main workflow

on:
  push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Start Setup
      run: echo "start setup"

    - name: Finish Setup
      run: echo "finish setup"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Start Build
      run: echo "build started"

    - name: Finish Build
      run: echo "build finished"

  testing:
    uses: ./.github/workflows/reusable-workflow.yml
